version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: logistica_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/logistica_db
    ports:
      - "8501:8501"

volumes:
  pgdata:
